#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# pipewire &
# pipewire-pulse &
# pipewire-media-session &
udiskie &
setxkbmap tr &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
picom -f &
# /usr/libexec/polkit-gnome-authentication-agent-1 & ## gnome polkit
# org.telegram.desktop &
# com.discordapp.Discord &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Pcmanfm state=floating follow=on
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a discord desktop='^4'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
